/*
RESOLVENDO QUESTOES AGREGAÇÃO NA PRATICA.
*/

-- SELECIONANDO BANCO DEDADOS A SER USADO
USE RESTAURANTE;

-- CALCULANDO A QUANTIDADE DE PEDIDOS
select * FROM pedido;
select sum(QUANTIDADE) FROM PEDIDO;

-- CALCULANDO QUANTIDADE DE CLIENTES UNICOS QUE REALIZARAM PEDIDOS
select sum(distinct id_cliente) FROM PEDIDO;

-- CALCULANDO MEDIA DE PREÇOS DOS PRODUTOS
select * FROM PRODUTO;
select round(avg(PRECO),2) AS MEDIA_PRECO FROM PRODUTO;

-- CALCULANDO O PREÇO MÁXIMO E O MÍNIMO DOS PRODUTOS
select max(PRECO) AS MAIOR_PREÇO FROM PRODUTO;
select min(PRECO) AS MENOR_PREÇO FROM PRODUTO;

-- SELECIOANNDO NOME E PREÇO DO PRODUTO E RANKEANDO OS 5 MAIS CAROS
select NOME, PRECO, row_number() OVER( ORDER BY PRECO DESC) AS RANKING_PREÇO FROM PRODUTO LIMIT 5;

-- SELECIONANDO A MÉDIA DOS PREÇOS DOS PRODUTOS AGRUPADOS POR CATEGORIA
select * FROM PRODUTO;
select CATEGORIA, round( avg(PRECO),2) AS MEDIA_PREÇO FROM PRODUTO group by CATEGORIA;
select * FROM PRODUTO;

-- SELECIONANDO O FORNECEDOR E MOSTRANDO A QUANTIDADE DE PRODUTOS POR FORNECEDOR. 
select * FROM INFO_PRODUTOS; 
 select FORNECEDOR, count(*) AS QUANTIDADE_PRODUTOS from INFO_PRODUTOS group by FORNECEDOR;
 
 -- SELECIONANDO OS FORNECEDORES QUE TEM MAIS DE UM PRODUTO CADASTRADO. 
select FORNECEDOR, count(*) AS QUANTIDADE_PRODUTOS
FROM INFO_PRODUTOS group by FORNECEDOR having count(*) > 1;

-- SELECIONAR OS CLIENTES QUE REALIZARAM APENAS UM PEDIDO
select id_cliente, count(*) as quantidade_pedidos from pedido group by id_cliente having count(*) = 1;





